# Generated by Django 4.1.4 on 2022-12-18 17:24

from django.db import migrations, models
import django.db.models.deletion
import inscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        ("inscripcion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscrito",
            name="institucion",
            field=models.ForeignKey(
                default=inscripcion.models.Institucion.get_default_institucion,
                on_delete=django.db.models.deletion.CASCADE,
                to="inscripcion.institucion",
            ),
        ),
    ]
