# Generated by Django 4.1.4 on 2022-12-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inscripcion", "0002_alter_inscrito_institucion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institucion",
            old_name="institucion",
            new_name="nombre",
        ),
        migrations.RemoveField(
            model_name="inscrito",
            name="fecha_reservada",
        ),
    ]
